/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AuthAccessTokenSchema extends BaseModel {
  static $columns = ['id', 'tokenableId', 'type', 'name', 'hash', 'abilities', 'createdAt', 'updatedAt', 'lastUsedAt', 'expiresAt'] as const
  $columns = AuthAccessTokenSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare tokenableId: number
  @column()
  declare type: string
  @column()
  declare name: string | null
  @column()
  declare hash: string
  @column()
  declare abilities: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column.dateTime()
  declare expiresAt: DateTime | null
}

export class BookmarkSchema extends BaseModel {
  static $columns = ['id', 'postId', 'userId', 'createdAt', 'updatedAt'] as const
  $columns = BookmarkSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare postId: number | null
  @column()
  declare userId: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class CategorySchema extends BaseModel {
  static $columns = ['id', 'name', 'slug', 'createdAt', 'updatedAt'] as const
  $columns = CategorySchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string | null
  @column()
  declare slug: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class CommentSchema extends BaseModel {
  static $columns = ['id', 'postId', 'userId', 'content', 'createdAt', 'updatedAt'] as const
  $columns = CommentSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare postId: number | null
  @column()
  declare userId: number | null
  @column()
  declare content: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class LikeSchema extends BaseModel {
  static $columns = ['id', 'postId', 'userId', 'createdAt'] as const
  $columns = LikeSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare postId: number | null
  @column()
  declare userId: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
}

export class PostSchema extends BaseModel {
  static $columns = ['id', 'title', 'slug', 'content', 'userId', 'createdAt', 'updatedAt', 'coverImage'] as const
  $columns = PostSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare title: string | null
  @column()
  declare slug: string | null
  @column()
  declare content: string | null
  @column()
  declare userId: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare coverImage: string | null
}

export class UserSchema extends BaseModel {
  static $columns = ['id', 'fullName', 'email', 'password', 'createdAt', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare fullName: string | null
  @column()
  declare email: string
  @column({ serializeAs: null })
  declare password: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
