/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  AccessToken: () => import('#controllers/access_token_controller'),
  Auth: () => import('#controllers/auth_controller'),
  Comments: () => import('#controllers/comments_controller'),
  NewAccount: () => import('#controllers/new_account_controller'),
  Posts: () => import('#controllers/posts_controller'),
  Profile: () => import('#controllers/profile_controller'),
  Likes: () => import('#controllers/likes_controller'),
  Bookmarks: () => import('#controllers/bookmarks_controller'),
  Profiles: () => import('#controllers/profiles_controller'),
}
